apiVersion: v2
name: prometheus
description: keptn basic
type: application
version: 25.14.0
appVersion: v2.50.0
dependencies: 
- name: prometheus
  version: "25.14.0"
  repository: "https://prometheus-community.github.io/helm-charts"

